# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-18 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_auto_20200611_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='cont_no',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='dated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='sanctioned_no',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
