# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_auto_20200618_2105'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='vendor',
        #     name='adharNo',
        #     field=models.CharField(max_length=12, null=True),
        # ),
        migrations.AddField(
            model_name='vendor',
            name='branchAddr',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='branchName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='firmNo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ifsc',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='panNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='properiterName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
