# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-24 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_auto_20200620_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='panNumber',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
