# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-27 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_auto_20200624_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='minorHead',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
