# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0013_auto_20200705_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorder',
            name='codeHead',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='dated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='deliveryAddress',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='gfrRule',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='minorHead',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='sanctionAutority',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='sanctionDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='sanctionNo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='unitAddress',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
