# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-27 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0014_auto_20200724_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitems',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
