# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-01 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0015_poitems_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorder',
            name='is_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poorder',
            name='is_csd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poorder',
            name='is_sanctioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poorder',
            name='member1_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='member1_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='member1_pos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='member2_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='member2_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='member2_pos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='member3_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='member3_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='member3_pos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='supplyOrderDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='supplyOrderNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='vendorAddress',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='vendorName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
