# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-02 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0016_auto_20200801_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorder',
            name='fileNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
