# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-14 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0017_poorder_fileno'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='vendor',
        #     name='adharNo',
        #     field=models.CharField(max_length=12, null=True),
        # ),
    ]
