# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0018_vendor_adharno'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorder',
            name='quoteDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='poorder',
            name='quoteNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='adharNo',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
