# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0019_auto_20200814_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='bankACno',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
