# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-22 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0020_auto_20200822_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='bankACno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
