# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-24 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0023_members_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorder',
            name='gstVal',
            field=models.FloatField(default=0.0),
        ),
    ]
