# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-25 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0024_poorder_gstval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('invoiceNo', models.CharField(max_length=100, null=True)),
                ('invoiceDate', models.DateField(null=True)),
                ('postingDate', models.DateField(null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('unitFileNo', models.CharField(max_length=100, null=True)),
                ('crvNo', models.CharField(max_length=100, null=True)),
                ('crvDate', models.DateField(null=True)),
                ('accntLedger', models.CharField(max_length=500)),
                ('po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poContingent', to='ERP.PoOrder')),
            ],
        ),
    ]
