# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-26 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0025_contingent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingent',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contingentUnit', to=settings.AUTH_USER_MODEL),
        ),
    ]
