# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0026_contingent_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingent',
            name='accntLedger',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
