# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-06 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0018_auto_20200811_2245'),
        ('ERP', '0028_auto_20200903_0637'),
    ]

    operations = [
    ]
