# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-09 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0029_merge_20200906_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poorder',
            name='quotationDate',
        ),
        migrations.RemoveField(
            model_name='poorder',
            name='quotationNo',
        ),
    ]
