# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_auto_20200204_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='walletValue',
            field=models.FloatField(default=0.0),
        ),
    ]
