# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-14 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_profile_walletvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='walletValue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
