# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-14 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_contact'),
        ('HR', '0005_auto_20200214_1306'),
    ]

    operations = [
    ]
