# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-22 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_merge_20200214_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
