# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-22 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_profile_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='parent',
            new_name='parent_store',
        ),
    ]
