# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-02 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0008_auto_20200222_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='orderId',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
