# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-19 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_contact_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='displayPicture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parent_store',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='walletValue',
        ),
        migrations.AddField(
            model_name='profile',
            name='dateOfComm',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dateOfJoin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pNumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
