# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-08-16 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_auto_20200719_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.RemoveField(
            model_name='document',
            name='issuedBy',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
