# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='user',
        ),
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachmentType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='notebook',
        ),
        migrations.DeleteModel(
            name='page',
        ),
    ]
