# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-07 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0002_auto_20200204_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='originator',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.DeleteModel(
            name='chatMessage',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
